### ISSUE TITLE
Doesn Load: -  _lsf.so: undefined symbol: Py_InitModule4

### ISSUE THREAD

**Issue by shuklaz** [IBMSpectrumComputing/lsf-python-api#10]
Doesn't work with Python 2.7.11 and LSF 9.1.3

whoami@vlpt-someone:~ >--> python
Python 2.7.11 (default, Jan 20 2016, 13:52:18)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-48)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from pythonlsf import lsf
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/hls/share/python/latest/lib/python2.7/site-packages/pythonlsf/lsf.py", line 5, in <module>
> > >     import _lsf
> > > **ImportError: /hls/share/python/latest/lib/python2.7/site-packages/pythonlsf/_lsf.so: undefined symbol: Py_InitModule4**

**Comment by xawangyd** [comment]
For LSF 10.1.0.2 or earlier version, the compatibility is not guaranteed if you update LSF at a later time. To avoid this compatibility issue, update LSF to version 10.1.0.3, or later, then rebuild and reinstall the LSF Python API package.

**Comment by adamsla** [comment]
Dom,

Is there an option in the setup.py to use static linking?  Is this included in the README.md?

Larry

**Comment by xawangyd** [comment]
No option in the setup.py to use static linking Py_InitModule4
The Compatibility & Supported Environment sections  in the readme file mentioned this.
```
The following versions are tested: Python 2.6.6, 2.7.15, 3.0, 3.6.0, 3.7.0

For LSF 10.1.0.2 or earlier version, the compatibility is not guaranteed
  	if you update LSF at a later time. To avoid this compatibility issue, 
  	update LSF to version 10.1.0.3, or later, then rebuild and reinstall the 
  	LSF Python API package.

```

**Comment by xawangyd** [comment]
When building LSF 9.1.3 with the latest LSF python API, will print the prompts of the compatibility to users

```
# python setup.py build
running build
running build_py
copying pythonlsf/lsf.py -> build/lib.linux-x86_64-2.7/pythonlsf
running build_ext
building '_lsf' extension
swigging pythonlsf/lsf.i to pythonlsf/lsf_wrap.c
swig -python -I/scratch/dev/isv/xawangyd/install_dir/lsf/lsf_9.1.3/9.1/linux2.6-glibc2.3-x86_64/lib/../../include/lsf/ -DOS_HAS_THREAD -D_REENTRANT -DNOTDEFINEFLAG_PYTHONAPI_KEYVALUE_T -DNOLSFVERSION -o pythonlsf/lsf_wrap.c pythonlsf/lsf.i
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -I/scratch/dev/isv/xawangyd/install_pkg/lsf/lsf-python-api-master/pythonlsf -I/usr/include/python2.7 -c pythonlsf/lsf_wrap.c -o build/temp.linux-x86_64-2.7/pythonlsf/lsf_wrap.o -m64 -I/scratch/dev/isv/xawangyd/install_dir/lsf/lsf_9.1.3/9.1/linux2.6-glibc2.3-x86_64/lib/../../include/lsf/ -Wno-strict-prototypes -DNOTDEFINEFLAG_PYTHONAPI_KEYVALUE_T -DNOLSFVERSION -DOS_HAS_THREAD -D_REENTRANT -Wp,-U_FORTIFY_SOURCE -O0
gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/pythonlsf/lsf_wrap.o -L/scratch/dev/isv/xawangyd/install_dir/lsf/lsf_9.1.3/9.1/linux2.6-glibc2.3-x86_64/lib -L/usr/lib64 -lc -lnsl -llsbstream -llsf -lbat -lrt -lpython2.7 -o build/lib.linux-x86_64-2.7/pythonlsf/_lsf.so -m64

Warning: The compatibility of the LSF Python API package is not guaranteed 
         if you update LSF at a later time. This is because your current 
         version of LSF does not release the
         /scratch/dev/isv/xawangyd/install_dir/lsf/lsf_9.1.3/9.1/linux2.6-glibc2.3-x86_64/lib/liblsbstream.a file.
         To avoid this compatibility issue, update LSF to version 10.1.0.3, 
         or later, then rebuild and reinstall the LSF Python API package.

#
```

**Comment by adamsla** [comment]
Thank you.
