### ISSUE TITLE
setup.py build gives ValueError: zero length field name in format

### ISSUE THREAD

**Issue by Andretility** [IBMSpectrumComputing/lsf-python-api#67]
[lsf-python-api]# python setup.py build
Traceback (most recent call last):
File "setup.py", line 81, in
set_gccflag_lsf_version()
File "setup.py", line 54, in set_gccflag_lsf_version
with open('{}/lsf.conf'.format(_lsf_envdir), 'r') as f:
ValueError: zero length field name in format

**Comment by Andretility** [comment]
added pull request #66
